<?php
/**
 * Implements hook_block_info().
 */
function islandora_global_sm2_block_info() {
  return array(
    'global_sm2' => array(
      'info' => 'SoundManager2 Player',
      'cache' => DRUPAL_NO_CACHE,
    ),
  );
}


/**
 *  Implements hook_block_view().
 */
function islandora_global_sm2_block_view($delta) {
  $block = array();
  if ($delta == 'global_sm2') {
    if (file_exists(libraries_get_path('fontawesome') . '/css/font-awesome.css')) {
      drupal_add_css(libraries_get_path('fontawesome') . '/css/font-awesome.css');
    }

    drupal_add_css(drupal_get_path('module', 'islandora_audiojs_global') . '/css/audiojs_global.css');
    $block['subject'] = '';
    $block['content'] = islandora_global_sm2_content();
  }
  return $block;
}

/**
 * Generate the content of the global player block.
 */
function islandora_global_sm2_content() {

  $sm2_path = libraries_get_path("SoundManager2");
  drupal_add_js($sm2_path . "/script/soundmanager2.js", array('group' => JS_LIBRARY, 'weight' => 0)); //TODO: minify me

  // Add bar-ui
  drupal_add_css($sm2_path . '/demo/bar-ui/css/bar-ui.css');
  // Add my custom css.
  drupal_add_css(drupal_get_path('module', 'islandora_global_sm2') . '/css/player.css');
// make this and add it on document ready or something.
  drupal_add_js(drupal_get_path('module', 'islandora_global_sm2') . '/js/initialize.js', array('group' => JS_DEFAULT, 'weight' => 5));

  // Add this to behaviours with heavier weight.
  drupal_add_js($sm2_path . '/demo/bar-ui/script/bar-ui.js', array('group' => JS_THEME, 'weight' => 9));

  $content = array();
  $content['#theme'] = 'islandora_global_sm2_bar_ui';
  $content['a'] = array('#markup' => 'foo'); // Theme needs a render element.
  return $content;
}

/**
 * Implements hook_theme().
 */
function islandora_global_sm2_theme() {
  return array(
    'islandora_global_sm2_bar_ui' => array(
      'template' => 'theme/islandora-global-sm2-bar-ui',
      'variables' => array(),
    ),
  );
}