<?php
/**
 * Implements hook_block_info().
 */
function islandora_global_sm2_block_info() {
  return array(
    'global_sm2' => array(
      'info' => 'Global SoundManager2 Player',
      'cache' => DRUPAL_NO_CACHE,
    ),
  );
}

/**
 *  Implements hook_block_view().
 */
function islandora_global_sm2_block_view($delta) {
  $block = array();
  if ($delta == 'global_sm2') {
    $block['subject'] = '';
    $block['content'] = islandora_global_sm2_content();
  }
  return $block;
}

/**
 * Generate the content of the global player block.
 */
function islandora_global_sm2_content() {
  $content = array();

  if (file_exists(libraries_get_path('fontawesome') . '/css/font-awesome.css')) {
    drupal_add_css(libraries_get_path('fontawesome') . '/css/font-awesome.css');
  }
  $sm2_path = libraries_get_path("soundmanager2");
  // Add the soundmanager2 javascript file, either the minified one or the regular one.
  //drupal_add_js($sm2_path . "/script/soundmanager2.js", array('group' => JS_LIBRARY, 'weight' => 0));
  drupal_add_js($sm2_path . "/script/soundmanager2-nodebug-jsmin.js", array('group' => JS_LIBRARY, 'weight' => 0));

  $mod_path = drupal_get_path('module', 'islandora_global_sm2');

  // Add CSS
  drupal_add_css($mod_path . '/bar-ui/css/bar-ui.css');
  drupal_add_css(drupal_get_path('module', 'islandora_global_sm2') . '/css/player.css');

  // Add swf path for flash fallback.
  $swf_url = file_create_url($sm2_path . "/swf/");
  $content['#attached']['js'][] = array(
    'type' => 'setting',
    'data' => array('islandora_global_sm2' => array('url' => $swf_url)),
  );

  // Create playlist before initializing player.
  $content['#attached']['js'][] = array(
    'type' => 'file',
    'data' => $mod_path . '/js/initialize.js',
    'group' => JS_THEME,
    'weight' => 5,
  );
  // Initialize Player.
  $content['#attached']['js'][] = array(
    'type' => 'file',
    'data' => $mod_path . '/bar-ui/script/bar-ui.js',
    'group' => JS_THEME,
    'weight' => 9
  );
  // Append to initialized player.
  $content['#attached']['js'][] = array(
    'type' => 'file',
    'data' => $mod_path . '/js/postinit.js',
    'group' => JS_THEME,
    'weight' => 10
  );

  $content['#theme'] = 'islandora_global_sm2_bar_ui';
  $content['a'] = array('#markup' => 'foo'); // Theme needs a render element.
  return $content;
}

/**
 * Implements hook_theme().
 */
function islandora_global_sm2_theme() {
  return array(
    'islandora_global_sm2_bar_ui' => array(
      'template' => 'theme/islandora-global-sm2-bar-ui',
      'variables' => array(),
    ),
  );
}